apiVersion: v2
name: sonarqube
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: sonarqube
    version: 1.1.9+137
    repository:  https://SonarSource.github.io/helm-chart-sonarqube