kube-prometheus-stack:
  alertmanager:
    enabled: false

  grafana:
    adminPassword: "Qwerty1234%"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: cert-manager
        kubernetes.io/ingress.class: nginx
      hosts:
        - grafana.k8sproject.ml
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.k8sproject.ml

  prometheus:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: cert-manager
        kubernetes.io/ingress.class: nginx
      hosts:
        - prometheus.k8sproject.ml
      tls:
        - secretName: prometheus-tls
          hosts:
            - prometheus.k8sproject.ml